# Generated by Django 5.1.8 on 2025-04-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
